In [1]:
import os
import numpy as np
import pandas as pd
import geostatspy 

In [7]:
import csv

In [2]:
os.chdir("c:/Users\Jorge\Desktop\sgem datos") 
print("Directory changed")

Directory changed


In [9]:
#convierte archivos dat a csv
with open('mitch.dat', 'r') as input_file:
    lines = input_file.readlines()
    newLines = []
    for line in lines:
        newLine = line.strip('').split()
        newLines.append(newLine)

with open('mitch.csv', 'w') as output_file:
    file_writer = csv.writer(output_file)
    file_writer.writerows(newLines)

In [15]:
df=pd.read_csv("mitch-2.csv") #df is data frame
#print(df.iloc[0:20,:])
df=df.dropna()
df.head()

X        Y          Z  Copper   Moly
1  36226.0  27295.1  869.50000    0.05  0.000
3  36226.0  27295.1  866.75000    0.02  0.000
5  36226.0  27295.1  863.70001    0.03  0.007
7  36226.0  27295.1  860.65002    0.00  0.000
9  36226.0  27295.1  857.59998    0.20  0.000

In [16]:
df.describe().transpose()

count          mean         std          min       25%          50%  \
X       10649.0  35263.918114  589.487799  33260.30000  34846.00  35337.00000   
Y       10649.0  28165.478759  340.272869  27041.90000  27957.10  28197.00000   
Z       10649.0    913.353123  124.768404    604.83002    818.00    897.84998   
Copper  10649.0      0.252618    0.268567      0.00000      0.07      0.18000   
Moly    10649.0      0.011340    0.032939      0.00000      0.00      0.00300   

             75%        max  
X       35695.80  38348.800  
Y       28442.10  29160.100  
Z        1001.30   1268.550  
Copper      0.35      4.320  
Moly        0.01      1.499

In [204]:
df=df.rename (columns={'facies_threshold_0.3':'facies','permeability':'perm','acoustic_impedance':'ai'})
df.head()

X     Y  facies  porosity    perm     ai
0   565  1485       1    0.1184   6.170  2.009
1  2585  1185       1    0.1566   6.275  2.864
2  2065  2865       2    0.1920  92.297  3.524
3  3575  2655       1    0.1621   9.048  2.157
4  1835    35       1    0.1766   7.123  3.979

In [205]:
df_subset=df.iloc[0:5,2:7]
print(df_subset)

   facies  porosity    perm     ai
0       1    0.1184   6.170  2.009
1       1    0.1566   6.275  2.864
2       2    0.1920  92.297  3.524
3       1    0.1621   9.048  2.157
4       1    0.1766   7.123  3.979


In [206]:
zeros=np.zeros(200)
df['zero']=pd.Series(zeros)  #Series tiene que ir con mayúscula
df.head()

X     Y  facies  porosity    perm     ai  zero
0   565  1485       1    0.1184   6.170  2.009   0.0
1  2585  1185       1    0.1566   6.275  2.864   0.0
2  2065  2865       2    0.1920  92.297  3.524   0.0
3  3575  2655       1    0.1621   9.048  2.157   0.0
4  1835    35       1    0.1766   7.123  3.979   0.0

In [207]:
df=df.drop("zero",axis=1)
df.head()

X     Y  facies  porosity    perm     ai
0   565  1485       1    0.1184   6.170  2.009
1  2585  1185       1    0.1566   6.275  2.864
2  2065  2865       2    0.1920  92.297  3.524
3  3575  2655       1    0.1621   9.048  2.157
4  1835    35       1    0.1766   7.123  3.979

In [210]:
df['porosity100']=df['porosity']*100
df['pem/por']=df['perm']/df['porosity']
#df=df.drop("pem*por",axis=1)
df.head()

X     Y  facies  porosity    perm     ai  porosity100     pem/por
0   565  1485       1    0.1184   6.170  2.009        11.84   52.111486
1  2585  1185       1    0.1566   6.275  2.864        15.66   40.070243
2  2065  2865       2    0.1920  92.297  3.524        19.20  480.713542
3  3575  2655       1    0.1621   9.048  2.157        16.21   55.817397
4  1835    35       1    0.1766   7.123  3.979        17.66   40.334088

In [211]:
df['tporosity']=np.where(df['porosity']>=0.12,'high','low')
df.head()

X     Y  facies  porosity    perm     ai  porosity100     pem/por  \
0   565  1485       1    0.1184   6.170  2.009        11.84   52.111486   
1  2585  1185       1    0.1566   6.275  2.864        15.66   40.070243   
2  2065  2865       2    0.1920  92.297  3.524        19.20  480.713542   
3  3575  2655       1    0.1621   9.048  2.157        16.21   55.817397   
4  1835    35       1    0.1766   7.123  3.979        17.66   40.334088   

  tporosity  
0       low  
1      high  
2      high  
3      high  
4      high

In [212]:
df['perm_cutoff']=np.where(df['porosity']>=0.12,df['perm'],0.0001)
df.head()

X     Y  facies  porosity    perm     ai  porosity100     pem/por  \
0   565  1485       1    0.1184   6.170  2.009        11.84   52.111486   
1  2585  1185       1    0.1566   6.275  2.864        15.66   40.070243   
2  2065  2865       2    0.1920  92.297  3.524        19.20  480.713542   
3  3575  2655       1    0.1621   9.048  2.157        16.21   55.817397   
4  1835    35       1    0.1766   7.123  3.979        17.66   40.334088   

  tporosity  perm_cutoff  
0       low       0.0001  
1      high       6.2750  
2      high      92.2970  
3      high       9.0480  
4      high       7.1230

In [213]:
df.set_value(1,'porosity',np.NaN)
print('Number of null values in our Data Frame =',str(df.isnull().sum().sum()))
NaN_rows=df[df['porosity'].isnull()]
print(NaN_rows)

Number of null values in our Data Frame = 1
      X     Y  facies  porosity   perm     ai  porosity100    pem/por  \
1  2585  1185       1       NaN  6.275  2.864        15.66  40.070243   

  tporosity  perm_cutoff  
1      high        6.275  


C:\Users\Jorge\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.


In [215]:
df=df.dropna()
df.head()

X     Y  facies  porosity    perm     ai  porosity100     pem/por  \
0   565  1485       1    0.1184   6.170  2.009        11.84   52.111486   
2  2065  2865       2    0.1920  92.297  3.524        19.20  480.713542   
3  3575  2655       1    0.1621   9.048  2.157        16.21   55.817397   
4  1835    35       1    0.1766   7.123  3.979        17.66   40.334088   
5  3375  2525       1    0.1239   1.468  2.337        12.39   11.848265   

  tporosity  perm_cutoff  
0       low       0.0001  
2      high      92.2970  
3      high       9.0480  
4      high       7.1230  
5      high       1.4680

In [227]:
df_extract=df.loc[(df['porosity']>0.12)&(df['perm']>10)]
df_extract.head()

X     Y  facies  porosity     perm     ai  porosity100     pem/por  \
2   2065  2865       2    0.1920   92.297  3.524        19.20  480.713542   
6   2295  1325       1    0.1790   31.933  3.491        17.90  178.396648   
7   3715  3045       2    0.1914  116.781  2.187        19.14  610.141066   
13   545  3765       1    0.1817   14.311  3.045        18.17   78.761695   
15  1385  2415       2    0.1774   22.578  2.711        17.74  127.271702   

   tporosity  perm_cutoff  
2       high       92.297  
6       high       31.933  
7       high      116.781  
13      high       14.311  
15      high       22.578

In [226]:
por=df['porosity'].values
perm=df['perm'].values
df_new=pd.DataFrame({'porosity':por,'permeability':perm})
df_new.head()

porosity  permeability
0    0.1184         6.170
1    0.1920        92.297
2    0.1621         9.048
3    0.1766         7.123
4    0.1239         1.468

In [17]:
print(df.index)
print(df.columns)
print(df.values)

Int64Index([    1,     3,     5,     7,     9,    11,    13,    15,    17,
               19,
            ...
            21279, 21281, 21283, 21285, 21287, 21289, 21291, 21293, 21295,
            21297],
           dtype='int64', length=10649)
Index(['X', 'Y', 'Z', 'Copper', 'Moly'], dtype='object')
[[3.6226000e+04 2.7295100e+04 8.6950000e+02 5.0000000e-02 0.0000000e+00]
 [3.6226000e+04 2.7295100e+04 8.6675000e+02 2.0000000e-02 0.0000000e+00]
 [3.6226000e+04 2.7295100e+04 8.6370001e+02 3.0000000e-02 7.0000000e-03]
 ...
 [3.5447600e+04 2.8573100e+04 9.9700000e+02 0.0000000e+00 0.0000000e+00]
 [3.5447600e+04 2.8573100e+04 9.9395001e+02 2.5999999e-01 0.0000000e+00]
 [3.5447600e+04 2.8573100e+04 9.9151001e+02 3.1800001e+00 6.0000000e-03]]


In [18]:
list(df)

['X', 'Y', 'Z', 'Copper', 'Moly']

In [234]:
col2_name=df.columns[3]
print(col2_name)
por1=df.values[1,3]
print('Porosity value for sample number 1 is '+str(por1)+'.')

porosity
Porosity value for sample number 1 is 0.192.


In [21]:
df.to_csv('mitch-3.csv')   #el nombre en rojo es con el
                           #que el archivo se descarga

In [77]:
#porosity_map_test=np.loadtxt("https://github.com/GeostatsGuy/GeoDataSets/blob/master/porosity_map.csv", delimiter=",")
#np.savetxt('https://github.com/GeostatsGuy/GeoDataSets/blob/master/porosity_map.csv',porosity_map,delimiter=',')
pixelplt(porosity_map,xmin,xmax,ymin,ymax,cell_size,vmin,vmax,"Porosity truth map","X(m)","Y(m)","Porosity (%)",cmap)

NameError: name 'pixelplt' is not defined

In [44]:
porosity_map = np.fromfile("https://github.com/GeostatsGuy/GeoDataSets/blob/master/porosity_truth_map.dat")

OSError: [Errno 22] Invalid argument: 'https://github.com/GeostatsGuy/GeoDataSets/blob/master/porosity_truth_map.dat'